#!/bin/bash

student=$1
ref=$2 

if [ -z $ref ]; then
    ref=tests/rast-$student
fi

compare -fuzz 2% $student $ref ae.png
composite $student $ref -alpha off -compose difference rawdiff.png
convert rawdiff.png -level 0%,8% diff.png
convert +append $ref $student ae.png rawdiff.png diff.png look_at_this_$student
rm ae.png rawdiff.png diff.png